### PR TITLE
WIP: Add more functionality

### PR DESCRIPTION
**Pull request by RQWorldblender**
Only the SPM importer and exporter are in a working state. The other files need major reworking. Intended to solve #4034 in `stk-code` as much as possible.

### CODE REVIEW

**Comment by 7wells** [comment]
Hello, I kind of stumbled over this (being no developer), wondering if it matters that "antarctica" is wrongly spelled "antractica" in several places. Sorry, this is maybe of very minor or no concern at all. Since I just begin to grasp the concept of GitHub etc., please forgive me my very minor comment. 😊

**Comment by RQWorldblender** [comment]
> Hello, I kind of stumbled over this (being no developer), wondering if it matters that "antarctica" is wrongly spelled "antractica" in several places. Sorry, this is maybe of very minor or no concern at all. Since I just begin to grasp the concept of GitHub etc., please forgive me my very minor comment. 😊

I alerted @Benau about this now, but I can solve this issue only on my end.

**Comment by Benau** [comment]
is it ready to be merged now?

**Comment by RQWorldblender** [comment]
I might do some more updates relating to the scope of objects that get exported. Most of the default exporters shipping with Blender export only the objects in the current scene, while the original versions of the scripts export every object in every scene. Once I have this done, I'll make the scripts ready to merge.

**Comment by RQWorldblender** [comment]
I might also need to change the material exporter so that it writes the image filename, not the image datablock name, as they can differ.

**Comment by RQWorldblender** [comment]
I might also need to change the material exporter so that it writes the image filename, not the image datablock name, as they can differ.
What about access to the wiki on the STK website? I might need it so that I can help update the documentation to include my version of the exporter scripts.

**Comment by Benau** [comment]
not sure @auriamg can create an account for Worldblender / XGhost so they can update wiki (they can be reached in discord) ....

**Comment by JulianSchoenbaechler** [comment]
> 
> 
> not sure @auriamg can create an account for Worldblender / XGhost so they can update wiki (they can be reached in discord) ....

That would be greatly appreciated.
Also just to mention it again, I still have a fork of Richard's work that diverged to a point where I am rewriting the whole Blender tools for STK: https://github.com/JulianSchoenbaechler/stk-blender/tree/workflow-improvements
It is not complete yet and far from working, I still need some weeks on it. However I believe it redefines how we work in Blender for STK, therefore it is in no way backwards compatible to the current tools we have. So consider this as an experimental and more artisitcal approach on kart/track design.
As soon as I have something working I'll create a detailed forum post about it and maybe open a separate pull request here (if wanted).

**Comment by Benau** [comment]
```
  <material name="stk_conelight_a.png" shader="alphablend"/>
  <material name="gfxGlow_red_a.png" shader="alphablend"/>
```
richard you can try export the latest emule blend, those lines should not be written, because i append the textures from global textures (media_repo/textures/*)

**Comment by RQWorldblender** [comment]
> ```
>   <material name="stk_conelight_a.png" shader="alphablend"/>
>   <material name="gfxGlow_red_a.png" shader="alphablend"/>
> ```
> 
> richard you can try export the latest emule blend, those lines should not be written, because i append the textures from global textures (media_repo/textures/*) 

Well, I think I could write additonal code to search in the assets path to check if a texture is in the assets directory, so that it doesn't try to overwrite whatever is configured there. Actually, by using the custom property editor, it is possible to delete the shader property in order to clear it for using the default config.

BTW, what changed in the latest version of the eMule kart?

**Comment by Benau** [comment]
you don't visit discord man!

**Comment by Benau** [comment]
our genuis and super sweet artist from Indonesia did an animation update on him

**Comment by RQWorldblender** [comment]
I just played all the animations from Blender, and they really have improved! Looks like the artist did a really good job!

I've got something that's going to be released in the next several days (new version of the Smash Ultimate karts), after which I will resume the work that I mentioned on my version of the exporter scripts. I haven't forgotten about them, but I prefer to not overwhelm myself with so much work at once.

**Comment by RQWorldblender** [comment]
Oh, it's good to see my exporter scripts working on Blender 2.90+! My effort at porting them is finally bearing fruit, by enabling more people to use newer Blender versions without sacrificing the ability to export STK objects!

**Comment by RQWorldblender** [comment]
@Benau I'm ready for you to take a review of all that I wrote so far. You might also want to tell me if there are still any outstanding issues that I have not yet caught.

**Pull request merged**
